apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-project6
  labels:
    app: hello-world-project6
    track: stable
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hello-world-project6
      track: stable
  template:
    metadata:
      labels:
        app: hello-world-project6
        track: stable
    spec:
      containers:
      - name: hello-world-project6
        image: myluc/udacity-devops:proj12
        ports:
        - containerPort: 8080
