apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-project6
  labels:
    app: hello-world-project6
    track: canary
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hello-world-project6
  template:
    metadata:
      labels:
        app: hello-world-project6
    spec:
      containers:
      - name: hello-world-project6
        image: myluc/udacity-devops:proj14
        ports:
        - containerPort: 8080
